### ISSUE TITLE
use of yarn instead of npm

### ISSUE THREAD

**Issue by kodeine** [mixmaxhq/eb-disable-npm#3]
yarn is way faster than npm, maybe we can start using yarn?

**Comment by wearhere** [comment]
Agreed, we use Yarn at Mixmax. However it's fastest of all to avoid doing _any_ sort of package installation on the EC2 instances (via this script) :) We use Yarn on our CI servers.

**Comment by wearhere** [comment]
Closing, let me know if you have more questions though!
